<h1> Homework 5

<h2> Sequential Quadratic Programming

In [16]:
import numpy as np
from scipy import linalg

In [23]:
def f(x):
    return x[0]**2 + (x[1]-3)**2

In [45]:
def df(x):
    return np.array([[2*x[0]],[2*(x[1]-3)]]).reshape([2,1])

In [47]:
def g(x):
    return np.array([[x[1]**2-2*x[0]],[(x[1]-1)**2+5*x[0]-15]]).reshape([2,1])

In [20]:
def dg(x):
    return np.array([[-2,2*x[1]],[5,2*(x[1]-1)]])

In [34]:
def lager(df,dg,mu):
    return df + np.matmul(mu,dg)

In [132]:
def solve_activeset(W,A,c,b,x):
    m1 = np.concatenate((W,np.transpose(A)),axis = 1)
    print(m1)
    m2 = np.concatenate((A,np.zeros((A.shape))),axis = 1)
    print(m2)
    M = np.concatenate((m1,m2),axis=0) #4x4
    print(M)
    U = np.concatenate((-c,b),axis=0)
    sol = M/U
    #sol_flat = sol.flatten()
    #s = sol_flat[0:x.size]
    #mu = sol_flat[x.size+1:sol_flat.size]
    return s,mu,sol.shape

In [133]:
solve_activeset(np.zeros([2,2]),dg(x0),df(x0),-g(x0),x0)

[[ 0.  0. -2.  5.]
 [ 0.  0.  2.  0.]]
[[-2.  2.  0.  0.]
 [ 5.  0.  0.  0.]]
[[ 0.  0. -2.  5.]
 [ 0.  0.  2.  0.]
 [-2.  2.  0.  0.]
 [ 5.  0.  0.  0.]]


(array([-0., -0.]),
 array([-2.5,  0. ,  0. ,  0.5,  0. , -2. ,  2. ,  0. ,  0. ,  0.5,  0. ,
         0. ,  0. ]),
 (4, 4))

In [21]:
def sqp(f,df,g,dg,x0,eps):
    x = x0 #1x2
    W = np.eye(x.size) #2x2
    mu_old = np.zeros(g(x).size) #1x2
    w = np.zeros(g(x).size) #1x2
    lag_norm = np.linalg.norm(lager(df(x),dg(x),mu_old))
    while lag_norm>eps:
        [s,mu_new] = qp()

array([[-2,  2],
       [ 5,  0]])

In [46]:
#### Testing Block ####
mu_old = np.zeros(g(x0).size)
mu_old.size
lager(df(x0),dg(x0),mu_old)
np.linalg.norm(lager(df(x0),dg(x0),mu_old))
df(x0).shape

(2, 1)

In [113]:
x0 = np.array([1,1])
eps = 1e-5
A = np.array([[2,1],[3,2]])
B = np.array([[1,1],[1,2]])
np.zeros([2,2])


array([[0., 0., 2., 3.],
       [0., 0., 1., 2.]])